name: Pytest

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      runs-on:
        required: true
        type: string

jobs:
  pyinstaller:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: sanjacob/pipenv-requirements@v1
        with:
          from-pipfile: true
          dev: true

      - name: Run PyInstaller
        run: python packaging/pyinst.py

      - if: startsWith(inputs.runs-on, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-latest
          path: dist/BBSync.app

      - if: startsWith(inputs.runs-on, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-latest
          path: dist/BBSync/**
